"""Initial migration.

Revision ID: ba091f7401f2
Revises: 
Create Date: 2020-11-14 19:50:44.611397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba091f7401f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_entry',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.Column('activity', sa.Text(), nullable=False),
    sa.Column('target', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_entry')
    # ### end Alembic commands ###
