# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ci

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make install-deps-py-dev
        make install-deps-js-dev
    - name: Lint
      run: |
        make lint

  # unit-test:
  #   runs-on: ubuntu-latest
  #   needs: lint
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python 3.6
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.6
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       make install-deps
  #   - name: Unit test
  #     run: |
  #       make unit-tests-py

  # integration-test:
  #   runs-on: ubuntu-latest
  #   needs: unit-test
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python 3.6
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.6
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       make install-deps
  #   - name: Integration test
  #     run: |
  #       make integration-tests-py